### ISSUE TITLE
plasma 6?

### ISSUE THREAD

**Issue by slynobody** [Nyre221/Kiview#12]
Does this work with dolphin in plasma 6?

**Comment by Nyre221** [comment]
@slynobody 
Hi

Kiview has already been ported to Qt6/Plasma6.   
You can use the flatpak version if you are interested in trying it: https://flathub.org/apps/io.github.nyre221.kiview
the flatpak version should work on Plasma 5 as well.

Note: There is a more up-to-date version on invent.kde.org, but for now it does not integrate with dolphin like the flatpak version does and cannot be used:  https://invent.kde.org/danagost/Kiview

The version on **Invent** is a version of kiview that is being modified to become an official kde application.    
The one on github uses a hack to interact with dolphin and has been removed from the new version on **invent**.

I clarify this because some users are confused about the difference between the two versions.
