### ISSUE TITLE
Kiview doesn't open previews when invoked via shortcut or context menu

### ISSUE THREAD

**Issue by tam1m** [Nyre221/Kiview#7]
I can't get Kiview to work on my machine. It just opens with the message "This name is not activatable".

Tested with v1.0.2  aswell as master (8c2c51b9886fa7b44dfaf9ea82ad0b8f598350dc) built by myself.

I'm not sure how to debug this.

[Kooha-2024-04-22-11-20-14.webm](https://github.com/Nyre221/Kiview/assets/472185/3d9ad8f5-7242-4ec6-9369-e5540aebfff5)

**Comment by Nyre221** [comment]
That seems to be a QDBus error message and not one from Kiview specifically.

Try:
1)Open dolphin
2) Press F4 to open the built-in terminal
3) In the terminal write `kiview` or `flatpak run io.github.nyre221.kiview --shortcut`

Some more information should appear.

What distribution do you have?
Kiview currently uses the system clipboard to take the path from Dolphin and it is possible that some calls are not 
working.
I'm wondering if you have any protection that is blocking QDBus and that's why it's giving that error.

**Comment by tam1m** [comment]
Alright, it is because I had Klipper disabled (via tray settings), since I just don't use it  After enabling it Kiview works fine. Didn't realise it depends on klipper.

**Comment by Nyre221** [comment]
> Alright, it is because I had Klipper disabled (via tray settings), since I just don't use it After enabling it Kiview works fine. Didn't realise it depends on klipper.

Kiview will become an official KDE project and there will be no need for these tricks/hacks anymore.

Have a nice day.
